package com.recipegrace.bbc.grmr

/**
  * Created by Ferosh Jacob on 12/24/16.
  */
trait GrammarKeywords {

  val ZONE = "zone"
  val ENV = "env"
  val SIMPLENAME = "name"
  val NUMWORKERS = "workers"
  val IMAGE = "image"
  val INITIALSCRIPT = "initialScript"
  val VERSION = "version"
  val INITIALSCRIPTTIMEOUT = "initialScriptTimeOut"
  val CONTAINER = "container"
  val PROPERTIES = "properties"
  val MAINCLASS = "mainClass"
  val MAINPYFILE = "mainPyFile"
  val JARLOCATION = "jarLocation"
  var OTHERPYFILES = "otherPyFiles"
  val PROPS = "props"
  val ARGS = "args"
  val USERNAME = "username"
  val PASSWORD = "password"
  val URL = "url"
  val REPOSITORY = "repository"
  val REPOBRANCH = "repoBranch"
  val SPARKJOB = "sparkjob"
  val PYSPARKJOB = "pysparkjob"
  val PYTHONJOB = "pythonjob"
  val SBTJOB = "sbtjob"
  val PIPELINE = "pipeline"
  val NEXUS = "nexus"
  val ARTIFACTORY = "artifactory"
  val CLUSTER = "cluster"
  val DELETE = "delete"
  val ON = "on"
  val RUN = "run"
  val CLOUDWORKSPACE = "cloudWorkspace"
  val FROM ="from"

  val PERCENTAGE = "%"
  val EQUAL = "="
  val OPENCURLY = "{"
  val CLOSECURLY = "}"
  val COMMA = ","
  val VAR ="var"
  val JSON ="json"
  val TRUE ="true"
  val FALSE = "false"
  val PLUS="+"
  val MINUS="-"
  val DOUBLEQUAL="=="
  val openBracket="("
  val closeBracket=")"
  val WEBSERVICEPOST = "webservicepost"
  val WEBSERVICEGET = "webserviceget"
}
